apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxwwws.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  version: v1
  scope: Namespaced
  names:
    plural: nginxwwws
    singular: nginxwww
    kind: NginxWww
    shortNames:
      - nw
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            html:
              type: string