apiVersion: "sample.javaoperatorsdk/v1"
kind: NginxWww
metadata:
  name: mynginx-hello
spec:
  html: |
    <html>
      <head>
        <title>Hello Operator World</title>
      </head>
      <body>
        Hellooooo!! Operators!!
      </body>
    </html>